[build]
builder = "NIXPACKS"
command = "pnpm -r run build"

[install]
command = "pnpm install"

[deploy]
startCommand = "pnpm --filter ./apps/api-gateway start & pnpm --filter ./apps/auth-service start & pnpm --filter ./apps/project-service start & pnpm --filter ./apps/ai-service start & pnpm --filter ./apps/realtime-service start"
restartPolicyType = "ON_FAILURE"