# =================================================
# APPLICATION
# =================================================
spring.application.name=notification-service
server.port=${SERVER_PORT:8085}

# =================================================
# APP ENV
# =================================================
app.env=${NODE_ENV:development}
app.frontend-url=${FRONTEND_URL:http://localhost:3000}

# =================================================
# RABBITMQ
# =================================================
spring.rabbitmq.host=${RABBITMQ_HOST:127.0.0.1}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}

# RabbitMQ listener
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=10
spring.rabbitmq.listener.simple.prefetch=5

# =================================================
# POSTGRESQL DATABASE
# =================================================
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:smartcollab}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =================================================
# REDIS
# =================================================
spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.database=${REDIS_DB:0}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.data.redis.timeout=60000

# =================================================
# MAIL SMTP
# =================================================
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =================================================
# LOGGING
# =================================================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.amqp=INFO
logging.level.org.hibernate.SQL=DEBUG