version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sc-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # Web UI quản lý
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - sc-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: sc-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - sc-net

networks:

  sc-net:
    driver: bridge

